# Generated by Django 6.0.2 on 2026-02-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='risk_score',
            new_name='overall_risk_score',
        ),
        migrations.RemoveField(
            model_name='document',
            name='summary',
        ),
        migrations.AddField(
            model_name='document',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
