# Generated by Django 6.0.2 on 2026-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_risk_score_document_overall_risk_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
